### ISSUE TITLE
Modern Browsers might use Intersection Observer

### ISSUE THREAD

**Issue by topaxi** [runspired/ember-radar#3]
I'm not familiar with the ember-radar implementation, but the Intersection Observer might get a smoother experience than scroll and resize events in modern Browsers?

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
https://wicg.github.io/IntersectionObserver/

Currently only supported in Chrome 51 and Firefox 52 though :)

I just stumbled upon the API and thought it might be of interest, feel free to close this issue if this doesn't apply here at all :)

**Comment by runspired** [comment]
@topaxi this doesnt use scroll and resize events (at least, not in it's latest state, we've yet to publish this on it's own since we arent dont extracting it). This is actually a better IO.
